# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
version: '1.0.{build}'
branches:
  only:
    - 'main'
    - 'main-libressl'
    - 'main-quictls'
    - 'main-boringssl'
    - 'main-mini'
    - 'dev'
    - 'dev-libressl'
    - 'dev-quictls'
    - 'dev-boringssl'
    - 'dev-mini'
    - 'test'
    - 'test-libressl'
    - 'test-quictls'
    - 'test-boringssl'
    - 'test-mini'
# https://www.appveyor.com/docs/build-environment/#build-worker-images
# https://www.appveyor.com/docs/linux-images-software/
image: 'Ubuntu2204'
services:
  - 'docker'
clone_depth: 8
build:
  verbosity: 'detailed'
environment:
  CW_LLVM_MINGW_DL: '1'
  CW_LLVM_MINGW_ONLY: '0'
  CW_MAP: '0'
  CW_JOBS: '2'
  SIGN_CODE_GPG_PASS:
    secure: 'wPf2iGvsKmSiXoTO7P6OoKYeRfRpuym4t/Xmq/9EprJUVzh8VXxLjcWgbd6CaA8y'
  SIGN_CODE_KEY_PASS:
    secure: 'YwtMnlHu3c6WDBY0GExfb6NxqQELKhJ1SrNV6aSh7a7sE1DEwcpR+J09MN3PDKl/'
  SIGN_PKG_KEY_ID: '99480C09BC89B68A07643F308C8F5B1419BDCAB8'
  SIGN_PKG_GPG_PASS:
    secure: '2LRzDmPXxl5ab+4RPfQLa7lAQZ1RH1MAXpiV5DkVgRxSDs8YpYutB3OvLnY2OETd'
  SIGN_PKG_KEY_PASS:
    secure: 'mV/nb16oXTF7b56NYzJro+Md07bfhtwqN6tAcZGCyda+DDwtrZhwS3GihROHJjp2'
  DEPLOY_GPG_PASS:
    secure: 'SxpZpEtfZoIav9uQiokFpHK9jBOSD9i2CPrTQ5cyucZ0EuyqYqFLAt66SJtnm07x'
  DEPLOY_KEY_PASS:
    secure: 'pSOhCTGiXFbOaY83f17iP2QX9HFznO1Va2DyMGhs9aP79i14Mbk3ukn3qhPF/wIT'
  DO_NOT_TRACK: '1'
  DOCKER_CONTENT_TRUST: '1'
build_script:
  - sh: |
      export CW_CONFIG="${APPVEYOR_REPO_BRANCH}-win"
      . ./_versions.sh
      docker trust inspect --pretty "${DOCKER_IMAGE}"
      time docker pull "${DOCKER_IMAGE}"
      docker images --digests
      time docker run --volume="$(pwd):$(pwd)" --workdir="$(pwd)" \
        --env-file=<(env | grep -a -E \
          '^(CW_|SIGN_|DEPLOY_|APPVEYOR_|CI_|DO_NOT_TRACK)') \
        "${DOCKER_IMAGE}" \
        sh -c ./_ci-linux-debian.sh

artifacts:
  - path: '*-*-mingw*.*'
    name: 'package'
  - path: 'all-mingw*.*'
    name: 'all'

# init:
#   - sh: curl --disable --user-agent '' --fail --silent --location --proto-redir =https 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
