# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT
---
# https://docs.github.com/actions/learn-github-actions
name: daily
on:
  workflow_dispatch:
  #schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  #- cron: '29 20 * * *'

permissions: {}

env:
  CW_MAP: '1'
  CW_JOBS: '4'
  CW_PKG_NODELETE: '1'
  CW_PKG_FLATTEN: '1'
  DO_NOT_TRACK: '1'
  DOCKER_CONTENT_TRUST: '1'

jobs:
  win:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 8
      - name: 'build'
        env:
          CW_LLVM_MINGW_DL: '1'
          CW_LLVM_MINGW_ONLY: '1'
        run: |
          export CW_CONFIG='dev-win-x64-openssl-zlibng-thinlto'
          export CW_REVISION="$(TZ=UTC date +'%Y%m%d')"
          . ./_versions.sh
          docker trust inspect --pretty "${DOCKER_IMAGE}"
          time docker pull "${DOCKER_IMAGE}"
          docker images --digests
          time docker run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
            --env-file <(env | grep -a -E \
              '^(CW_|GITHUB_|DO_NOT_TRACK)') \
            "${DOCKER_IMAGE}" \
            sh -c ./_ci-linux-debian.sh

      - name: 'list dependencies'
        run: cat urls.txt
      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v4
        with:
          name: 'curl-windows-daily-tool'
          retention-days: 42
          path: curl-*-*-*/curl*
      - uses: actions/upload-artifact@v4
        with:
          name: 'curl-windows-daily'
          retention-days: 42
          path: |
            *-*-mingw*.*
            urls.txt
