# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT
---
name: REUSE
on:
  push:
    branches:
      - main
      - dev
      - test

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'REUSE compliance check'
        uses: fsfe/reuse-action@v2
